# Generated by Django 5.0.1 on 2024-01-05 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(verbose_name='Created date')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('unit_of_measurement_id', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='Created date')),
                ('user_id', models.IntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minv.materials')),
            ],
        ),
    ]
