# Generated by Django 5.0.1 on 2024-01-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minv', '0004_rename_material_id_stock_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='unit_of_measurement_id',
            new_name='unit_of_measurement',
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ticket_id',
            field=models.IntegerField(verbose_name='Delivery / Issue Ticket No.'),
        ),
    ]
