# Generated by Django 5.0.1 on 2024-01-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minv', '0005_rename_material_id_entry_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user_id',
        ),
    ]
