# Generated by Django 5.0.1 on 2024-01-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minv', '0006_remove_entry_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
