# Generated by Django 5.0.1 on 2024-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minv', '0007_material_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('INWARD', 'Inward'), ('Issue', 'Issue')], default='INWARD', max_length=10),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
