spring.application.name=ordercollectorchestrator

#Application
info.app.name=ordercollectorchestrator
info.app.description=ordercollectorchestrator
info.app.version=1.0

service.version=1.0
server.address=0.0.0.0
server.port=8080
server.servlet.context-path=/ordercollectorchestrator
springfox.documentation.swagger.v2.path=/api-docs

api.contact.url=http://api.macys.com
api.version=1.0
api.license.url=http://license.macys.com
apiContextIdListing=true
api.description=This API is for ordercollectorchestrator service.
apiContextIdPattern=*
api.title=ordercollectorchestrator
api.contact.name=Macys
api.termsOfService=api.termsOfService
api.contact.email=api@macys.com
api.license.name=Proprietary

controller.collectorder.path=/v1/orders
controller.checkresponse.path=/v1/lock/orders

#Actuators
management.endpoints.web.base-path=/actuator
management.endpoints.web.cors.allowed-origins=true
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

# The configuration for prometheus
# @visibility public
# @scope environment
management.endpoint.metrics.enabled=true

# Configuration for prometheus
# @visibility public
# @scope environment
management.endpoints.web.exposure.include=*

# The configuration for prometheus
# @visibility public
# @scope environment
management.endpoint.prometheus.enabled=true

# The configuration for prometheus
# @visibility public
# @scope environment
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

#Logging and Tracing
spring.cloud.gcp.logging.enabled=true
spring.cloud.gcp.trace.enabled=true
spring.sleuth.async.enabled=false


################## Resilience4j #############
#CircuitBreaker Configs
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.slowCallRateThreshold=100
resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold=60s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=100
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=100
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=false

#CircuitBreaker Instances
resilience4j.circuitbreaker.instances.ordercollectorchestrator-cb.baseConfig=default
resilience4j.circuitbreaker.instances.ordercollectorchestratorackmchub-cb.baseConfig=default

resilience4j.circuitbreaker.instances.ordercollectorchestrator-cb.recordFailurePredicate=com.macys.uop.order.ordercollectorchestrator.predicate.OrdercollectorchestratorFailurePredicate
resilience4j.circuitbreaker.instances.ordercollectorchestrator-cb.recordFailureReasonCodes=UOP-GEN-E05007,UOP-GEN-E05040,UOP-GEN-E05013,UOP-GEN-E05015,UOP-GEN-E05041,UOP-GEN-E05044
resilience4j.circuitbreaker.instances.ordercollectorchestratorackmchub-cb.recordFailurePredicate=com.macys.uop.order.ordercollectorchestrator.predicate.OrdercollectorchestratorAckMchubFailurePredicate
resilience4j.circuitbreaker.instances.ordercollectorchestratorackmchub-cb.recordFailureReasonCodes=UOP-GEN-E05007,UOP-GEN-E05040,UOP-GEN-E05013,UOP-GEN-E05015,UOP-GEN-E05041,UOP-GEN-E05044

pubsub.msg.nack.valid.errorcodes.list=UOP-GEN-E05046

#Retry Configs
resilience4j.retry.configs.default.maxRetryAttempts=1
resilience4j.retry.configs.default.waitDuration=2s

#Retry Instances
resilience4j.retry.instances.createLockTransaction-rt.baseConfig=default
resilience4j.retry.configs.default.retryExceptionPredicate=com.macys.uop.foundation.core.utils.predicate.AbortedTransactionAndNetworkFailureRetryPredicate

#tomcat server config
server.tomcat.mbeanregistry.enabled=true
server.tomcat.connection-timeout=60000
server.tomcat.keep-alive-timeout=-1
server.tomcat.threads.max=200

#Logging
taskexecutor.taskexecutor.logsummary.enabled=true
taskexecutor.eventstate.config.purgeRecordsOnSuccess=false

#Pubsub Publishers/Subscribers
topic.subscription.collectorder.name=pull__collectorder_request_dev__collectorder_create
topic.subscription.checkresponse.name=pull__fraudprocessor_onsuccess_dev__collectorder_request
topic.subscription.digitalcheckout.mcom.name=pull-m-checkout-order-collect-info-uop-dev
topic.subscription.digitalcheckout.blcom.name=pull-blm-checkout-order-collect-info-uop-dev
event_onsuccess.channel_name=event_onsuccess_dev
ordercollectorchestrator.input.channel.name=collectorder_request_dev
collectorder_fraudacknowledgment.channel_name=collectorder_fraudacknowledgment_dev
errorprocessor_errorrequest.channel_name=projects/mtech-scm-common-np/topics/errorprocessor_errorrequest_dev
ordercreation_onsuccess.channel_name=ordercreation_onsuccess_dev
eventlog.publish.channel.name=${event_onsuccess.channel_name}
collectorder_response.channel_name=collectorder_response_dev

#Order Error Publisher Channel
ordererror.publish.channel.name=exception_onsuccess_dev

#Remote service properties
message.duplicationcheck.service.base_uri=https://oms-dev.msc.gcp.cloudrts.net/messagestore/v1/messages
ordercollect-service.collectorder.base_uri=https://oms-dev.msc.gcp.cloudrts.net/ordercollect/v1/orders/collect
orderenrichment-service.orderenrichment.base_uri=https://oms-dev.msc.gcp.cloudrts.net/orderenrichment/v1/orders/enrich
lockmanager-service.createLockTransaction.base_uri=https://oms-dev.msc.gcp.cloudrts.net/lockmanager/v1/orders/locks


#Profile Integration
profileevaluator.profilemanager.profile.type=ORDER
profileevaluator.profilemanager.base_uri=https://oms-dev.msc.gcp.cloudrts.net/profilemanager/v1/config/orders/profiles
firebase.credential.path=${GOOGLE_APPLICATION_CREDENTIALS}
profileevaluator.profilemanager.profile.collection.name=dev__profiles

#Business Config
#Firestore(collection name should be added in properties project)
businessconfigmanager.businessconfig.collection.name=businessconfig
businessconfigmanager.businessconfig.collection.name.v2=businessconfig_v2

#Error Processor Configuration
errorprocessor.dispatchdeadline=100s
errorprocessor.errorretrymaxcount=1
errorprocessor.errorretryduration=1
errorprocessor.errorlogmaxcount=0
errorprocessor.errorlogduration=0
errorprocessor.selfretrymaxcount=1
errorprocessor.selfretryduration=1
errorprocessor.requesttype=oms-op-task-queue

errorprocessor.createerror.requesttype=${errorprocessor.requesttype}
errorprocessor.createerror.publish.channel.name=${errorprocessor_errorrequest.channel_name}

#default.resttemplate.connectiontimeout.ms=600000
#default.resttemplate.readtimeout.ms=600000

#Step Config
command.collectorder.steps=ORDER_LOGEVENT,ORDER_VALIDATE,ORDER_STAMPPROFILE,ORDER_ENHANCEBOSSPLUS,ORDER_CREATE,ORDER_LOCK,PARTNER_FULFILLMENT_ID_LOCK,ORDER_ENRICH,ORDER_PUBLISHCREATESUCCESS
command.collectorder.steps.recovery=ORDER_RECOVERYSTATE,ORDER_LOGEVENT
command.checkfraudresponse.steps=ORDER_PUBLISHMCHUBACK

#GCP ProjectId,Spanner details
spring.cloud.gcp.spanner.project-id=mtech-wms-oms-nonprod
spring.cloud.gcp.spanner.instance-id=orderplatform
spring.cloud.gcp.spanner.database=order_db_dev
spring.profiles.active=local

#EPF Table Excluded Errorcode
errorList.400error=UOP-ORD-E10011,UOP-ORD-E10012,UOP-GEN-E10021,UOP-ORD-E10023,UOP-ORD-E10028

spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=2
spring.cloud.gcp.pubsub.subscriber.executor-threads=20
default.masking.enabled=false

#Rest template connection pool configurations
default.resttemplate.connectionmanager.maxtotal=300
default.resttemplate.connectionmanager.defaultmaxperroute=100
default.resttemplate.requestconfig.sockettimeout=600000
default.resttemplate.requestconfig.connectionrequesttimeout=5000
default.resttemplate.requestconfig.connecttimeout=600000

management.metrics.web.server.request.autotime.percentiles=0.5,0.75,0.80,0.90,0.95

# temporary profile change
order.temoporary.file = Y
order.profile.pickup = PICKUP
order.profile.mixed = MIXEDORDER

kill-switch-r3=false

#Handle Node ShutDowns
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=2m
enableR3businessconfig=true

management.health.defaults.enabled=false
custom.pubsub.listener.shutdown.waittime=180000

#BossPlus Flow flag
bossplus.enabled=true
