<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.macys.uop</groupId>
    <artifactId>op-foundation</artifactId>
    <version>2.0.57</version>
  </parent>
  <artifactId>util-core</artifactId>
  
  <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>problem</artifactId>
			<version>${problem.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${mapstruct.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-messaging</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot2</artifactId>
			<version>${resilience4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-circuitbreaker</artifactId>
			<version>${resilience4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-bulkhead</artifactId>
			<version>${resilience4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-retry</artifactId>
			<version>${resilience4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-all</artifactId>
			<version>${resilience4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>${springfox-boot-starter.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
		</dependency>
    	<dependency>
            <groupId>io.opencensus</groupId>
            <artifactId>opencensus-api</artifactId>
            <version>${opencensus.version}</version>
        </dependency>
		<dependency>
			<groupId>io.opencensus</groupId>
			<artifactId>opencensus-impl</artifactId>
			<version>${opencensus.version}</version>
		</dependency>
		<dependency>
    		<groupId>io.opencensus</groupId>
    		<artifactId>opencensus-exporter-stats-prometheus</artifactId>
    		<version>${opencensus.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-api-mockito2</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4-rule-agent</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.hamcrest</groupId>
					<artifactId>hamcrest-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
	<properties>
		<sonar.exclusions>
			**/com/macys/uop/foundation/core/utils/CommonStatusCode.java,
			**/com/macys/uop/foundation/core/utils/Constant.java,
			**/com/macys/uop/foundation/core/utils/audit/*.java,
			**/com/macys/uop/foundation/core/utils/common/*.java,
			**/com/macys/uop/foundation/core/utils/eventlog/*.java,
			**/com/macys/uop/foundation/core/utils/exception/Error.java,
			**/com/macys/uop/foundation/core/utils/exception/ErrorDetail.java,
			**/com/macys/uop/foundation/core/utils/exception/ProblemUtil.java,
			**/com/macys/uop/foundation/core/utils/execution/*.java,
			**/com/macys/uop/foundation/core/utils/future/CompletableFutureCompletionRuntimeException.java,
			**/com/macys/uop/foundation/core/utils/logging/*.java,
			**/com/macys/uop/foundation/core/utils/mapper/*.java,
			**/com/macys/uop/foundation/core/utils/masking/ApplicationMaskingConfiguration.java,
			**/com/macys/uop/foundation/core/utils/masking/CreditCardNumberMasker.java,
			**/com/macys/uop/foundation/core/utils/masking/MaskingConfig.java,
			**/com/macys/uop/foundation/core/utils/masking/MaskingUtil.java,
			**/com/macys/uop/foundation/core/utils/masking/XMLParsingException.java,
			**/com/macys/uop/foundation/core/utils/message/*.java,
			**/com/macys/uop/foundation/core/utils/msg/publisher/MessagePublisherClient.java,
			**/com/macys/uop/foundation/core/utils/msg/subscriber/AbstractCommonStreamHelper.java,
			**/com/macys/uop/foundation/core/utils/ordererror/OrderErrorMessage.java,
			**/com/macys/uop/foundation/core/utils/ordererror/OrderErrorMessageBuilder.java,
			**/com/macys/uop/foundation/core/utils/ordererror/OrderErrorMessagePublisher.java,
			**/com/macys/uop/foundation/core/utils/rest/client/RestClient.java,
			**/com/macys/uop/foundation/core/utils/rest/client/RestClientRequest.java,
			**/com/macys/uop/foundation/core/utils/rest/client/RestClientResponse.java,
			**/com/macys/uop/foundation/core/utils/rest/client/RestClientResponseBuilder.java,
			**/com/macys/uop/foundation/core/utils/security/*.java,
			**/com/macys/uop/foundation/core/utils/spring/*.java,
			**/com/macys/uop/foundation/core/utils/msg/subscriber/SubscriberInfo.java,
			**/com/macys/uop/foundation/core/utils/swagger/*.java,
			**/com/macys/uop/foundation/core/utils/task/*.java,
			**/com/macys/uop/foundation/core/utils/test/*.java,
			**/com/macys/uop/foundation/core/utils/trace/*.java,
			**/com/macys/uop/foundation/core/utils/validation/*.java,
			**/com/macys/uop/foundation/core/utils/web/configuration/*.java,
			**/com/macys/uop/foundation/core/utils/web/advice/AbstractGlobalExceptionAdvice.java,
			**/com/macys/uop/foundation/core/utils/web/advice/GlobalExceptionAdvice.java
		</sonar.exclusions>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.7</version>
				<configuration>
					<excludes>
						<exclude>**/JsonUtils.class</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<id>default-prepare-agent</id>
						<phase>process-test-classes</phase>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
					<execution>
						<id>default-check</id>
						<phase>test</phase>
						<goals>
							<goal>check</goal>
						</goals>
						<configuration>
							<rules>
								<rule>
									<limits>
										<limit>
											<counter>INSTRUCTION</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.0</minimum>
										</limit>
										<limit>
											<counter>LINE</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.0</minimum>
										</limit>
										<limit>
											<counter>BRANCH</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.0</minimum>
										</limit>
										<limit>
											<counter>COMPLEXITY</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.0</minimum>
										</limit>
										<limit>
											<counter>METHOD</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.0</minimum>
										</limit>
										<limit>
											<counter>CLASS</counter>
											<value>COVEREDRATIO</value>
											<minimum>0.0</minimum>
										</limit>
									</limits>
								</rule>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

